Select * from customer limit 30
--Q1. What is the total revenue generated by male vs. female customers
select gender, Sum(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as "Average Product Rating"
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
select shipping_type,round(avg(purchase_amount),2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type
--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
select subscription_status,
Count (customer_id) as total_customer,
Round(avg(purchase_amount),2) as avg_spend,
Round(SUM(purchase_amount),2) as revenue
from customer
group by subscription_status
order by avg_spend, revenue desc

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5

--Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment. 
with customer_type as (
select customer_id, previous_purchases,
CASE 
    when previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM customer)

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment

--Q8. What are the top 3 most purchased products within each category? 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
Select subscription_status,
       COUNT(customer_id) AS repeat_buyers
from customer
Where previous_purchases > 5
group by subscription_status
--Q10. What is the revenue contribution of each age group? 
Select age_group, Round(SUM(purchase_amount),2) as revenue
from customer
group by age_group

